import { CountryModel } from './../models/country-model';

export const COUNTRYLIST: CountryModel[] = [
  {
    iso: 'US',
    name: 'United States',
    states: [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'District of Columbia',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming'
   ],
   phoneCode: '+1',
  },
  {
    iso: 'NG',
    name: 'Nigeria',
    states: [
      'Abia',
      'Abuja Federal Capital',
      'Adamawa',
      'Akwa Ibom',
      'Anambra',
      'Bauchi',
      'Bayelsa',
      'Benue',
      'Borno',
      'Cross River',
      'Delta',
      'Ebonyi',
      'Edo',
      'Ekiti',
      'Enugu',
      'Gombe',
      'Imo',
      'Jigawa',
      'Kaduna',
      'Kano',
      'Katsina',
      'Kebbi',
      'Kogi',
      'Kwara',
      'Lagos',
      'Nassarawa',
      'Niger',
      'Ogun',
      'Ondo',
      'Osun',
      'Oyo',
      'Plateau',
      'Rivers',
      'Sokoto',
      'Taraba',
      'Yobe',
      'Zamfara'
   ],
   phoneCode: '+234',
  },
  {
    iso: 'GB',
    name: 'United Kingdom',
    states: [ 
      'Aberconwy and Colwyn',
      'Aberdeen City',
      'Aberdeenshire',
      'Anglesey',
      'Angus',
      'Antrim',
      'Argyll and Bute',
      'Armagh',
      'Avon',
      'Ayrshire',
      'Bath and NE Somerset',
      'Bedfordshire',
      'Belfast',
      'Berkshire',
      'Berwickshire',
      'BFPO',
      'Blaenau Gwent',
      'Buckinghamshire',
      'Caernarfonshire',
      'Caerphilly',
      'Caithness',
      'Cambridgeshire',
      'Cardiff',
      'Cardiganshire',
      'Carmarthenshire',
      'Ceredigion',
      'Channel Islands',
      'Cheshire',
      'City of Bristol',
      'Clackmannanshire',
      'Clwyd',
      'Conwy',
      'Cornwall/Scilly',
      'Cumbria',
      'Denbighshire',
      'Derbyshire',
      'Derry/Londonderry',
      'Devon',
      'Dorset',
      'Down',
      'Dumfries and Galloway',
      'Dunbartonshire',
      'Dundee',
      'Durham',
      'Dyfed',
      'East Ayrshire',
      'East Dunbartonshire',
      'East Lothian',
      'East Renfrewshire',
      'East Riding Yorkshire',
      'East Sussex',
      'Edinburgh',
      'England',
      'Essex',
      'Falkirk',
      'Fermanagh',
      'Fife',
      'Flintshire',
      'Glasgow',
      'Gloucestershire',
      'Greater London',
      'Greater Manchester',
      'Gwent',
      'Gwynedd',
      'Hampshire',
      'Hartlepool',
      'Hereford and Worcester',
      'Hertfordshire',
      'Highlands',
      'Inverclyde',
      'Inverness-Shire',
      'Isle of Man',
      'Isle of Wight',
      'Kent',
      'Kincardinshire',
      'Kingston Upon Hull',
      'Kinross-Shire',
      'Kirklees',
      'Lanarkshire',
      'Lancashire',
      'Leicestershire',
      'Lincolnshire',
      'Londonderry',
      'Merseyside',
      'Merthyr Tydfil',
      'Mid Glamorgan',
      'Mid Lothian',
      'Middlesex',
      'Monmouthshire',
      'Moray',
      'Neath & Port Talbot',
      'Newport',
      'Norfolk',
      'North Ayrshire',
      'North East Lincolnshire',
      'North Lanarkshire',
      'North Lincolnshire',
      'North Somerset',
      'North Yorkshire',
      'Northamptonshire',
      'Northern Ireland',
      'Northumberland',
      'Nottinghamshire',
      'Orkney and Shetland Isles',
      'Oxfordshire',
      'Pembrokeshire',
      'Perth and Kinross',
      'Powys',
      'Redcar and Cleveland',
      'Renfrewshire',
      'Rhonda Cynon Taff',
      'Rutland',
      'Scottish Borders',
      'Shetland',
      'Shropshire',
      'Somerset',
      'South Ayrshire',
      'South Glamorgan',
      'South Gloucesteshire',
      'South Lanarkshire',
      'South Yorkshire',
      'Staffordshire',
      'Stirling',
      'Stockton On Tees',
      'Suffolk',
      'Surrey',
      'Swansea',
      'Torfaen',
      'Tyne and Wear',
      'Tyrone',
      'Vale Of Glamorgan',
      'Wales',
      'Warwickshire',
      'West Berkshire',
      'West Dunbartonshire',
      'West Glamorgan',
      'West Lothian',
      'West Midlands',
      'West Sussex',
      'West Yorkshire',
      'Western Isles',
      'Wiltshire',
      'Wirral',
      'Worcestershire',
      'Wrexham',
      'York'
   ],
   phoneCode: '+44',
  },
  {
    iso: 'GH',
    name: 'Ghana',
    states:
    [
       'Ashanti',
       'Brong-Ahafo',
       'Central',
       'Eastern',
       'Greater Accra',
       'Northern',
       'Upper East',
       'Upper West',
       'Volta',
       'Western'
    ],
   phoneCode: '+233',
  },
  {
    iso: 'CA',
    name: 'Canada',
    states: [
      'Alberta',
      'British Columbia',
      'Manitoba',
      'New Brunswick',
      'Newfoundland and Labrador',
      'Northwest Territories',
      'Nova Scotia',
      'Nunavut',
      'Ontario',
      'Prince Edward Island',
      'Quebec',
      'Saskatchewan',
      'Yukon Territory'
   ],
   phoneCode: '+1',
  }
];
